name: CI Pipeline

on:
  push:
    branches: [ trunk ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout head
      uses: actions/checkout@v2
    - uses: VUnit/vunit_action@v0.1.0
      with:
        run_file: src/vunit_run_script.py