name: ci pipeline

on:
  push:
    branches: [ trunk ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout head
      uses: actions/checkout@v2
    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: set up vunit
      run: |
        sudo apt-get install ghdl
        pip install vunit_hdl
    - name: run unit tests
      run: python /tests/vunit_run_script.py